### ISSUE TITLE
few isseus

### ISSUE THREAD

**Issue by firefigther0575** [cyberjunky/addon-p2000_rtlsdr#1]
few things i ran into

- after changing the config no restart possible.
- verbosity  default setting is debug, in the article you refer to  only set this to debug if needed.

- After starting the add on my node red crashed.

greets

**Comment by cyberjunky** [comment]
@firefigther0575 thank for testing, to be honest I was expecting some issues, but it runs here for days in a row without issues, filtering away thousands of events... I need some more information to see what is going on or needs fixing:

config issue:
What exactly is the problem when changing config (what do you change?) and what do you see happening?
Normally you just change, click 'Opslaan' if there is an issue with the format you get an error here.

Then go back to add-on's 'informatie' tab and click 'herstarten'

node-red crash:
I never used node-red, but since all addon's are docker images, they are separated completely from each other. Maybe ther share MQTT but they all have separated topics on that bus. What do you see in the log of node-red when it 'crashes'?

**Comment by firefigther0575** [comment]
after renaming/ or changing a capcode it wont restart.
if i can recreate it i will post the code thats genarating.
the node red issue could be my fault, that happend after a first instal of rtl sdr add on.

**Comment by firefigther0575** [comment]
i changed from normal to debug when i want to restart i got the next error: 

Can't start addon_83becdae_p2000_rtlsdr: 404 Client Error for http+docker://localhost/v1.42/containers/abb06a1909c3d96d36ffe031e0f6114e3bebfe0e15aa1897c2e98f3239626f62/start: Not Found ("No such container: abb06a1909c3d96d36ffe031e0f6114e3bebfe0e15aa1897c2e98f3239626f62")

**Comment by firefigther0575** [comment]
i have tested the "black" sdr receiver and the " Blue " from the wel known chinese distributers, i found that the blue one get real hot, could be that the usb fit is not the best, "loose" 
The black one has also usb fitting issue " to loose" for the usb port so it can be that you encounter a error. restarting the add-on and it runs for hours.
