### ISSUE TITLE
Error install P2000...

### ISSUE THREAD

**Issue by loewal** [cyberjunky/addon-p2000_rtlsdr#7]
Trying to install the addon renders this error:

The command '/bin/ash -o pipefail -c cd /tmp && git clone git://git.osmocom.org/rtl-sdr.git && cd rtl-sdr && mkdir build && cd build && cmake ../ -DINSTALL_UDEV_RULES=ON -DDETACH_KERNEL_DRIVER=ON && make && make install && cd / && rm -r /tmp/rtl-sdr' returned a non-zero code: 128

Can you help?

**Comment by joper112** [comment]
On line 13 it says: git://git.osmocom.org/rtl-sdr.git
I changed this to: https://gitea.osmocom.org/sdr/rtl-sdr.git and then it does install correctly. 
So my line 13 is now:  git clone https://gitea.osmocom.org/sdr/rtl-sdr.git && \

I have now downloaded the files separately and modified them so I could install it correctly again. However the application now runs as a local application instead of your repo



@cyberjunky can you change this maybe in this repo. I think its than working again for everyone 😄

**Comment by cyberjunky** [comment]
Thanks, just updated it in 1.0.2
